### ISSUE TITLE
error

### ISSUE THREAD

**Issue by puntoCL** [hackingcl/dateador#3]
root@kali:~/dateador# python dateador.py stalker

                   ╔═══╗  ╔╗        ╔╗
                   ╚╗╔╗║ ╔╝╚╗       ║║
                    ║║║╠═╩╗╔╬══╦══╦═╝╠══╦═╗
                    ║║║║╔╗║║║║═╣╔╗║╔╗║╔╗║╔╝
                   ╔╝╚╝║╔╗║╚╣║═╣╔╗║╚╝║╚╝║║
                   ╚═══╩╝╚╩═╩══╩╝╚╩══╩══╩╝
                      v1.1 by @unkndown

 Obtén los datos de una persona con el rut o nombre de ella:

 -Ejemplo con rut: 5519653-2
 -Ejemplo con nombre: Pedro Aguilar Toloza
 -Si tienes solo una parte del nombre, usa la opción stalker

 Ingresa un rut o nombre: 5519653-2

 [+] Buscando datos

+------------------------------------------+
Traceback (most recent call last):
  File "dateador.py", line 56, in <module>
    total = len(data['value'])
KeyError: 'value'

**Comment by hackingcl** [comment]
Fixed
